export const FETCH_TRAIN_DATA_REQUEST = "FETCH_TRAIN_DATA_REQUEST";
export const FETCH_TRAIN_DATA_SUCCESS = "FETCH_TRAIN_DATA_SUCCESS";
export const FETCH_STATION_NAMES_REQUEST = "FETCH_STATION_NAMES_REQUEST";
export const FETCH_STATION_NAMES_SUCCESS = "FETCH_STATION_NAMES_SUCCESS";
export const FETCH_STATION_NAMES_ERROR = "FETCH_STATION_NAMES_ERROR";
