export const FETCH_TRAIN_DATA_REQUEST = "FETCH_TRAIN_DATA_REQUEST";
export const FETCH_TRAIN_DATA_SUCCESS = "FETCH_TRAIN_DATA_SUCCESS";
export const FETCH_STATIONS_REQUEST = "FETCH_STATIONS_REQUEST";
export const FETCH_STATIONS_SUCCESS = "FETCH_STATIONS_SUCCESS";
export const FETCH_STATIONS_ERROR = "FETCH_STATIONS_ERROR";
export const SELECT_DEPARTURE_STATION = "SELECT_DEPARTURE_STATION";
export const SET_DEPARTURE_STATION = "SET_DEPARTURE_STATION";
export const SET_DESTINATION_STATION = "SET_DESTINATION_STATION";
